name: FBLib
version: 0.0.1
description: An open sourced library for checking if a server is running kettle, lava and any future hybrid implementations when possible.
author: Mallis
main: com.DisabledMallis.FBLib.Main
api-version: 1.14